modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Jeryn99/tardis-refined-rwf/issues"
license = "All Rights Reserved"

[[mods]]
modId = "tardis_refined_rwf"
version = "${version}"
displayName = "TARDIS Refined: Real World Flight"
authors = "Jeryn99, EdraxDoodles"
description = '''
An addon for TARDIS Refined that lets you fly your TARDIS exterior around the real world.
'''
#logoFile = ""

[[dependencies.tardis_refined_rwf]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tardis_refined_rwf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tardis_refined_rwf]]
modId = "tardis_refined"
mandatory = true
versionRange = "[2.1.6,)"
ordering = "AFTER"
side = "BOTH"
